include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build_base # build stage is running on Kubernetes cluster
  - build      # build stage is running on Kubernetes cluster
  - test       # test stage is running on slurm cluster

variables:
  PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/software/arbor_hohgant_cpu:$CI_COMMIT_SHORT_SHA

build-base:
  extends: .container-builder-dynamic-name
  stage: build_base
  variables:
    DOCKERFILE: ci/cscs/hohgant_cpu/Dockerfile.base
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/base/arbor_hohgant_cpu_base_image
    WATCH_FILECHANGES: 'ci/cscs/hohgant_cpu/Dockerfile.base'

build-arbor:
  extends: .container-builder
  stage: build
  variables:
    DOCKERFILE: ci/cscs/hohgant_cpu/Dockerfile
    DOCKER_BUILD_ARGS: '["BASE_IMG=$BASE_IMAGE"]'
    GIT_SUBMODULE_STRATEGY: recursive

# Note: hohgant has an MPI issue: doesn't allow multiple MPI runs in same job due to repeated
# MPI_Init/MPI_Finalize calls. Therefore, we test examples individually (each in different job).

test-single-node:
  extends: .container-runner-hohgant-zen2
  stage: test
  image: $PERSIST_IMAGE_NAME
  script:
    - cd /arbor.src
    - build/bin/unit-modcc
    - build/bin/unit-local
    - build/bin/unit
  variables:
    SLURM_JOB_PARTITION: normal
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    SLURM_CPUS_PER_TASK: 128
    SLURM_TIMELIMIT: "00:10:00"
    USE_MPI: "NO"

test-python-single-node:
  extends: .container-runner-hohgant-zen2
  stage: test
  image: $PERSIST_IMAGE_NAME
  script:
    - cd /arbor.src
    - python -m venv --system-site-packages /arbor.install
    - source /arbor.install/bin/activate
    - python -m unittest discover -v -s python
    - deactivate
  variables:
    SLURM_JOB_PARTITION: normal
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    SLURM_CPUS_PER_TASK: 128
    SLURM_TIMELIMIT: "00:10:00"
    USE_MPI: "NO"

bench-single-node:
  extends: .container-runner-hohgant-zen2
  stage: test
  image: $PERSIST_IMAGE_NAME
  script:
    - cd /arbor.src
    - scripts/run_cpp_examples.sh --with=bench
  variables:
    SLURM_JOB_PARTITION: normal
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    SLURM_CPUS_PER_TASK: 128
    SLURM_TIMELIMIT: "00:10:00"
    USE_MPI: "NO"

brunel-single-node:
  extends: .container-runner-hohgant-zen2
  stage: test
  image: $PERSIST_IMAGE_NAME
  script:
    - cd /arbor.src
    - scripts/run_cpp_examples.sh --with=brunel
  variables:
    SLURM_JOB_PARTITION: normal
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    SLURM_CPUS_PER_TASK: 128
    SLURM_TIMELIMIT: "00:10:00"
    USE_MPI: "NO"

test-distributed:
  extends: .container-runner-hohgant-zen2
  stage: test
  image: $PERSIST_IMAGE_NAME
  script:
    - cd /arbor.src
    - build/bin/unit-mpi
  variables:
    SLURM_JOB_PARTITION: normal
    SLURM_JOB_NUM_NODES: 2
    SLURM_NTASKS: 4
    SLURM_CPUS_PER_TASK: 64
    SLURM_TIMELIMIT: "00:10:00"
    USE_MPI: "YES"

bench-distributed:
  extends: .container-runner-hohgant-zen2
  stage: test
  image: $PERSIST_IMAGE_NAME
  script:
    - cd /arbor.src
    - scripts/run_cpp_examples.sh --with=bench -d
  variables:
    SLURM_JOB_PARTITION: normal
    SLURM_JOB_NUM_NODES: 2
    SLURM_NTASKS: 4
    SLURM_CPUS_PER_TASK: 64
    SLURM_TIMELIMIT: "00:10:00"
    USE_MPI: "YES"

brunel-distributed:
  extends: .container-runner-hohgant-zen2
  stage: test
  image: $PERSIST_IMAGE_NAME
  script:
    - cd /arbor.src
    - scripts/run_cpp_examples.sh --with=brunel -d
  variables:
    SLURM_JOB_PARTITION: normal
    SLURM_JOB_NUM_NODES: 2
    SLURM_NTASKS: 4
    SLURM_CPUS_PER_TASK: 64
    SLURM_TIMELIMIT: "00:10:00"
    USE_MPI: "YES"

remote-distributed:
  extends: .container-runner-hohgant-zen2
  stage: test
  image: $PERSIST_IMAGE_NAME
  script:
    - cd /arbor.src
    - scripts/run_cpp_examples.sh --with=remote -d
  variables:
    SLURM_JOB_PARTITION: normal
    SLURM_JOB_NUM_NODES: 2
    SLURM_NTASKS: 4
    SLURM_CPUS_PER_TASK: 64
    SLURM_TIMELIMIT: "00:10:00"
    USE_MPI: "YES"
